# Generated by Django 4.1.5 on 2023-07-13 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_rename_comment_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
