# Generated by Django 4.1.5 on 2023-07-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_rating_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
    ]
