# Generated by Django 4.1.5 on 2023-10-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0015_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient',
        ),
    ]
