# Generated by Django 4.1.5 on 2023-10-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0019_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_old',
        ),
    ]
