# Generated by Django 4.1.5 on 2023-10-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0021_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
