# Generated by Django 4.1.5 on 2023-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0022_rename_ingredient_ingredient_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
